/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnaliticaRouteImport } from './routes/_app/analitica'
import { Route as AppDiarioRouteImport } from './routes/_app/diario'
import { Route as AppFijosRouteImport } from './routes/_app/fijos'
import { Route as AppIaRouteImport } from './routes/_app/ia'
import { Route as AppMovimientosRouteImport } from './routes/_app/movimientos'
import { Route as AppPresupuestosRouteImport } from './routes/_app/presupuestos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliticaRoute = AppAnaliticaRouteImport.update({
  id: '/analitica',
  path: '/analitica',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppFijosRoute = AppFijosRouteImport.update({
  id: '/fijos',
  path: '/fijos',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimientosRoute = AppMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppPresupuestosRoute = AppPresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/analitica': typeof AppAnaliticaRoute
  '/diario': typeof AppDiarioRoute
  '/fijos': typeof AppFijosRoute
  '/ia': typeof AppIaRoute
  '/movimientos': typeof AppMovimientosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/analitica': typeof AppAnaliticaRoute
  '/diario': typeof AppDiarioRoute
  '/fijos': typeof AppFijosRoute
  '/ia': typeof AppIaRoute
  '/movimientos': typeof AppMovimientosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/_app/analitica': typeof AppAnaliticaRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/fijos': typeof AppFijosRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/movimientos': typeof AppMovimientosRoute
  '/_app/presupuestos': typeof AppPresupuestosRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/login'
    | '/analitica'
    | '/diario'
    | '/fijos'
    | '/ia'
    | '/movimientos'
    | '/presupuestos'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/beta'
    | '/login'
    | '/analitica'
    | '/diario'
    | '/fijos'
    | '/ia'
    | '/movimientos'
    | '/presupuestos'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/beta'
    | '/login'
    | '/_app/analitica'
    | '/_app/diario'
    | '/_app/fijos'
    | '/_app/ia'
    | '/_app/movimientos'
    | '/_app/presupuestos'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BetaRoute: typeof BetaRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analitica': {
      id: '/_app/analitica'
      path: '/analitica'
      fullPath: '/analitica'
      preLoaderRoute: typeof AppAnaliticaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fijos': {
      id: '/_app/fijos'
      path: '/fijos'
      fullPath: '/fijos'
      preLoaderRoute: typeof AppFijosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimientos': {
      id: '/_app/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AppMovimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presupuestos': {
      id: '/_app/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof AppPresupuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnaliticaRoute: typeof AppAnaliticaRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppFijosRoute: typeof AppFijosRoute
  AppIaRoute: typeof AppIaRoute
  AppMovimientosRoute: typeof AppMovimientosRoute
  AppPresupuestosRoute: typeof AppPresupuestosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnaliticaRoute: AppAnaliticaRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppFijosRoute: AppFijosRoute,
  AppIaRoute: AppIaRoute,
  AppMovimientosRoute: AppMovimientosRoute,
  AppPresupuestosRoute: AppPresupuestosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BetaRoute: BetaRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
